name: newsletter
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - pip:
      - fastmcp
      - requests
      - openai
      - jinja2
      - python-dotenv
      - markdown
      - twikit
