name: 🚀 Send AI-Agent Newsletter

on:
  # 1) Run every Monday at 08:00 UTC (adjust as needed)
  schedule:
    - cron:  '0 8 * * MON'
  # 2) Allow manual runs via “Run workflow” button
  workflow_dispatch:

jobs:
  send_newsletter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Fetch & send newsletter
        run: python main.py "ai agent"
        env:
          SMTP_HOST:      ${{ secrets.SMTP_HOST }}
          SMTP_PORT:      ${{ secrets.SMTP_PORT }}
          SMTP_USER:      ${{ secrets.SMTP_USER }}
          SMTP_PASS:      ${{ secrets.SMTP_PASS }}
          EMAIL_SENDER:   ${{ secrets.EMAIL_SENDER }}
          EMAIL_RECIPIENT:${{ secrets.EMAIL_RECIPIENT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NEWS_API_KEY:   ${{ secrets.NEWS_API_KEY }}
          S2_API_KEY:     ${{ secrets.S2_API_KEY }}
          GITHUB_TOKEN:   ${{ secrets.GITHUB_TOKEN }}
          # TWIKIT_* if you’re using Twitter
          TWIKIT_USERNAME:${{ secrets.TWIKIT_USERNAME }}
          TWIKIT_EMAIL:   ${{ secrets.TWIKIT_EMAIL }}
          TWIKIT_PASSWORD:${{ secrets.TWIKIT_PASSWORD }}
